/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;

import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "ToDo List Manager";
    }

    public void displayFirstMenu() {
        System.out.println("\n\t\tMain Menu");
        System.out.println("\n1. Open To Do List");//open up from file
        System.out.println("2. Display To Do Items");
        System.out.println("3. Edit To Do Item");
        System.out.println("4. Delete To Do Item");
        System.out.println("5. Save To Do List");
        System.out.println("6. Add Item To Do List");
        System.out.println("7. Exit");

        return;
    }

    private String callScanner(String prompt) {
        System.out.println(prompt);
        String response = scanner.nextLine();

        return response;
    }

    private void displayTaskList(ArrayList<Task> listOfTasks) {
        showTaskList(listOfTasks);
        askIfFinished();
    }

    private void askIfFinished() {
        String prompt = "\nWould you like to return to main menu (Y/N)? ";
        String responseReturned = callScanner(prompt);
        if (responseReturned.toUpperCase().equals("Y"))
            return;

        prompt = "\nWould you like to exit (Y/N)?";
        responseReturned = callScanner(prompt);
        if (responseReturned.toUpperCase().equals("Y"))
            System.exit(0);
        else
            return;
    }

    private void showTaskList(ArrayList<Task> listOfTasks) {
        System.out.println("\n\tList of Tasks");
        int count = 1;
        for (Task task : listOfTasks) {
            System.out.println(count + " - " + task.getName());
            count++;
        }
    }

    private void deleteTask(ArrayList<Task> listOfTasks) {
        showTaskList(listOfTasks);
        String prompt = "\nType the number of the item you wish to delete and hit enter. ";
        String responseReturned = callScanner(prompt);
        System.out.println("You chose to delete task #" + responseReturned);
        int responseReturnedInt = Integer.parseInt(responseReturned);
        int sizeOfTaskList = listOfTasks.size();
        if (sizeOfTaskList < responseReturnedInt) {
            System.out.println("invalid choice");
            askIfFinished();
        }
        else {
            listOfTasks.remove(responseReturnedInt - 1);
            showTaskList(listOfTasks);
            askIfFinished();
        }
    }

    private void editTask(ArrayList<Task> listOfTasks) {
        showTaskList(listOfTasks);
        String prompt = "\nType the number of the item you wish to edit and hit enter. ";
        String responseReturned = callScanner(prompt);
        System.out.println("You chose to delete task #" + responseReturned);
        int responseReturnedInt = Integer.parseInt(responseReturned);
        int sizeOfTaskList = listOfTasks.size();
        if (sizeOfTaskList < responseReturnedInt) {
            System.out.println("invalid choice");
            askIfFinished();
        }
        else {
            prompt= "\nType name of task and hit enter.";
            String editedTaskName = callScanner(prompt);
            Task task = listOfTasks.get(responseReturnedInt - 1);
            task.setName(editedTaskName);
            //listOfTasks.get(responseReturnedInt - 1).setName(editedTaskName);
            showTaskList(listOfTasks);
            askIfFinished();
        }
    }

    Scanner scanner = new Scanner(System.in);
    public static void main(String[] args) {
        App app = new App();

        Task task1 = new Task("Iron pants",LocalDate.of(2021,3,1),true,false);
        Task task2 = new Task("Rake Leaves",LocalDate.of(2020,5,15),false,true);
        Task task3 = new Task("Till garden",LocalDate.of(2021,1,31),false,true);
        ArrayList<Task> listOfTasks = new ArrayList<>();
        listOfTasks.add(task1);
        listOfTasks.add(task2);
        listOfTasks.add(task3);
        System.out.println(listOfTasks.size());
        System.out.println(listOfTasks.get(0).getName() + " " + listOfTasks.get(0).getDueDate() + " " + listOfTasks.get(0).getIsCompleted() + " " + listOfTasks.get(0).getIsInProgress());

        String responseReturned;
        do {
            app.displayFirstMenu();
            String prompt = "\nPlease input your option:";
            responseReturned = app.callScanner(prompt);
            System.out.println("\nYour response was " + responseReturned);
            switch (responseReturned) {
                case "1": //this option is for opening the file
                    System.out.println("You chose to open the to do list");
                    break;
                case "2":
                    app.displayTaskList(listOfTasks);
                    break;
                case "3":
                    app.editTask(listOfTasks);
                    break;
                case "4":
                    app.deleteTask(listOfTasks);
                    break;
                case "5": //this option is for saving to the file
                    System.out.println("You chose to save the to do list");
                    break;
                case "6":
                    prompt = "\nType in task that you would like to add.";
                    responseReturned = app.callScanner(prompt);
                    System.out.println("\nYour response was " + responseReturned);
                    Task newTask = new Task(responseReturned, LocalDate.of(2020,05,10),true, false);
                    listOfTasks.add(newTask);
                    app.displayTaskList(listOfTasks);
                    break;
                case "7":
                    System.out.println("You chose to exit");
                    break;
                default:
                    System.out.println("You chose an invalid option - Please enter a number between 1 and 6");
                    break;
            }
        } while (!responseReturned.equals("7"));
        app.scanner.close();
    }
}
