/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ToDo;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.type.CollectionType;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;



public class App {
    private static FileWriter file;

    public String getGreeting() {
        return "ToDo List Manager";
    }


    public void displayFirstMenu() {
        System.out.println("\n\tWhat would you like to do next?");
        System.out.println("\n  ");
        System.out.println("1. Display To Do Items");
        System.out.println("2. Edit To Do Item");
        System.out.println("3. Delete To Do Item");
        System.out.println("4. Save To Do List");
        System.out.println("5. Add Item To Do List");
        System.out.println("6. Exit");

    }

    private String callScanner(String prompt) {
        System.out.println(prompt);
        String response = scanner.nextLine();

        return response;
    }

    private void displayTaskList(ArrayList<Task> listOfTasks) {
        showTaskList(listOfTasks);
        askIfFinished();
    }

    private void askIfFinished() {
        String prompt = "\nWould you like to return to main menu (Y/N)? ";
        String responseReturned = callScanner(prompt);
        if (responseReturned.toUpperCase().equals("Y"))
            return;

        prompt = "\nWould you like to exit (Y/N)?";
        responseReturned = callScanner(prompt);
        if (responseReturned.toUpperCase().equals("Y"))
            System.exit(0);
        else
            return;
    }

    private void showTaskList(ArrayList<Task> listOfTasks) {
        System.out.println("\n\tTasks" + "\t\t\t Due Date" + "\t In Progress?" + "\t Completed?");
        int count = 1;
        for (Task task : listOfTasks) {
            System.out.println(count + " - " + task.getName() + "\t\t " + task.getDueDate() + "\t " + task.getInProgress() + "\t\t\t " +task.getCompleted());
            count++;
        }
    }

    private void deleteTask(ArrayList<Task> listOfTasks) {
        showTaskList(listOfTasks);
        String prompt = "\nType the number of the item you wish to delete and hit enter. ";
        String responseReturned = callScanner(prompt);
        System.out.println("You chose to delete task #" + responseReturned);
        int responseReturnedInt = Integer.parseInt(responseReturned);
        int sizeOfTaskList = listOfTasks.size();
        if (sizeOfTaskList < responseReturnedInt) {
            System.out.println("invalid choice");
            askIfFinished();
        }
        else {
            listOfTasks.remove(responseReturnedInt - 1);
            showTaskList(listOfTasks);
            askIfFinished();
        }
    }

    private void editTask(ArrayList<Task> listOfTasks) {
        showTaskList(listOfTasks);
        //need to add ability to edit more than just the name
        String prompt = "\nType the number of the item you wish to edit and hit enter. ";
        String responseReturned = callScanner(prompt);
        int responseReturnedInt = Integer.parseInt(responseReturned);
        int sizeOfTaskList = listOfTasks.size();
        if (sizeOfTaskList < responseReturnedInt) {
            System.out.println("invalid choice");
            askIfFinished();
        }
        else {
            prompt= "\nType the new name of task and hit enter.";
            String editedTaskName = callScanner(prompt);
            Task task = listOfTasks.get(responseReturnedInt - 1);
            task.setName(editedTaskName);
            showTaskList(listOfTasks);
            askIfFinished();
        }
    }

    private static void addTask(App app, ArrayList<Task> listOfTasks) {
        String prompt;
        prompt = "\nType in the name of the task that you would like to add.";
        String newTaskNameReturned = app.callScanner(prompt);
        prompt = "\nType in the due date of the task in format YYYYMMDD.";
        String newTaskDueDate = app.callScanner(prompt);
        int newTaskDueDateYear = Integer.parseInt(newTaskDueDate.substring(0, 4));
        int newTaskDueDateMo = Integer.parseInt(newTaskDueDate.substring(4, 6));
        int newTaskDueDateDay = Integer.parseInt(newTaskDueDate.substring(6, 8));
        prompt = "\nIs this new task in progress (y/n)?";
        String newTaskInProgress = app.callScanner(prompt);
        Boolean taskInProgress;
        if (newTaskInProgress.toUpperCase().equals("Y"))
            taskInProgress = true;
        else
            taskInProgress = false;
        prompt = "\nIs this new finished (y/n)?";
        String newTaskFinished = app.callScanner(prompt);
        Boolean taskFinished;
        if (newTaskFinished.toUpperCase().equals("Y"))
            taskFinished = true;
        else
            taskFinished = false;
        Task newTask = new Task(newTaskNameReturned, LocalDate.of(newTaskDueDateYear, newTaskDueDateMo, newTaskDueDateDay),taskInProgress, taskFinished);
        //I think listOfTasks is null here so not sure if I can just add - have to do something when adding first one?
        listOfTasks.add(newTask);
        app.displayTaskList(listOfTasks);
        return;
    }

        private static void writeListToFile (ArrayList < Task > taskList) {
            ObjectMapper obj = new ObjectMapper();
            String json = null;
            try {
                json = obj.writeValueAsString(taskList);
            } catch (JsonProcessingException e) {
                e.printStackTrace();
            }
            try {
                file = new FileWriter("/Git/JavaGettingStarted_ToDoList/Tasklist.json");
                file.write(json);
            } catch (IOException e) {
                e.printStackTrace();
            } finally {
                try {
                    file.flush();
                    file.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }

    private static ArrayList<Task> readFile() {
        //read file
        JSONParser parser = new JSONParser();
        ArrayList<JSONObject> jsonObject = null;
        try {
            Object obj = parser.parse(new FileReader("/Git/JavaGettingStarted_ToDoList/Tasklist.json"));
            jsonObject = (ArrayList<JSONObject>) obj;
        } catch (Exception e) {
            e.printStackTrace();
        }
        //map file
        String response = String.valueOf(jsonObject);
        ObjectMapper mapper = new ObjectMapper();
        List<Task> taskArray = null;
        try {
            CollectionType listType = mapper.getTypeFactory().constructCollectionType(ArrayList.class, Task.class);
            taskArray = mapper.readValue(response,listType);
        }catch (IOException e) {
            e.printStackTrace();
        }
        ArrayList<Task> listOfTasks = new ArrayList<>(taskArray);

        return listOfTasks;
    }

    private static void menuOptions(App app, ArrayList<Task> listOfTasks) {
        String responseReturned;
        String prompt;
        do {
            app.displayFirstMenu();
            prompt = "\nPlease input your option:";
            responseReturned = app.callScanner(prompt);
            switch (responseReturned) {
                case "1":
                    app.displayTaskList(listOfTasks);
                    break;
                case "2":
                    app.editTask(listOfTasks);
                    break;
                case "3":
                    app.deleteTask(listOfTasks);
                    break;
                case "4":
                    //need to be able to have them input file name since I'm allowing them to create new file
                    writeListToFile(listOfTasks);
                    System.out.println("The file has been saved to C:Git>JavaGettingStarted_ToDo_list>Tasklist.json");
                    app.askIfFinished();
                    break;
                case "5":
                    addTask(app, listOfTasks);
                    break;
                case "6":
                    System.out.println("You chose to exit.  Thank you.");
                    break;
                default:
                    System.out.println("You chose an invalid option - Please enter a number between 1 and 6");
                    break;
            }
        } while (!responseReturned.equals("6"));
    }


    Scanner scanner = new Scanner(System.in);

    public static void main(String[] args) {
        App app = new App();
        ArrayList<Task> listOfTasks = null;

        String responseReturned;
        String prompt = "\nWould you like to open your Existing file or start creating a New one?(E/N)";
        responseReturned = app.callScanner(prompt);
        if (responseReturned.toUpperCase().equals("E")) {
            listOfTasks = readFile();
            System.out.println("Your existing file contains the following items");
            app.displayTaskList(listOfTasks);
            menuOptions(app, listOfTasks);
        }else
            addTask(app, listOfTasks);
        //need to work on add code when it is a new file

        app.scanner.close();
    }



}
